version: "3.8"

services:
  nextjs-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add any environment variables your app needs here
      # - DATABASE_URL=your_database_url
      # - API_KEY=your_api_key
    restart: unless-stopped
    container_name: nextjs-portfolio-app
    networks:
      - portfolio-network

  odoo:
    image: odoo:17.0
    container_name: odoo-ecommerce
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      # Database connection settings
      - HOST=${ODOO_DB_HOST}
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo # User data, attachments
      - odoo-config:/etc/odoo # Configuration files
      - odoo-addons:/mnt/extra-addons # Custom modules
    depends_on:
      - postgres
    networks:
      - portfolio-network

  postgres:
    image: postgres:15
    container_name: odoo-postgres
    restart: unless-stopped
    environment:
      # Database configuration
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
    volumes:
      # Persistent storage for database
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - portfolio-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # SSL certificates from Let's Encrypt
    depends_on:
      - nextjs-portfolio
    restart: unless-stopped
    container_name: nextjs-portfolio-nginx
    networks:
      - portfolio-network

  # Portainer - Docker GUI Management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

# Add volumes section
volumes:
  portainer_data:
  odoo-web-data: # Stores Odoo files, attachments, user data
  odoo-config: # Stores Odoo configuration
  odoo-addons: # Stores custom Odoo modules
  postgres-data: # Stores PostgreSQL database files
