name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3 # Updated to latest version
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          debug: true # Enable debug mode to see more details
          script: |
            echo "Starting deployment..."
            cd nextjs-portfolio || exit 1
            echo "Current directory: $(pwd)"
            git pull origin main
            echo "Running deploy script..."
            ./deploy.sh
            echo "Deployment completed!"
