name: Deploy to VPS

on:
  push:
    branches: [main] # Change to your default branch if different
  workflow_dispatch: # Allows manual triggering from GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/$(whoami)/nextjs-portfolio
            git pull origin main
            ./deploy.sh
